services:
  - type: web
    name: telegram-schedule-bot
    env: python
    region: frankfurt
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "8531196180:AAHTRMQ1dgNqbdnJM9Cy4ByoCv6FPlzpYsI"
    autoDeploy: true
